### ISSUE TITLE
json中写的人设并没有起到作用，但让她发表情包可以做到，下再中的思想钢印都没一点效果，不知什么原因造成

### ISSUE THREAD

**Issue by hutao01-miku** [chordfish-k/emoticon#2]

**Comment by chordfish-k** [comment]
注意：本插件的json仅作为一个使用示范，并非是完美的。
关于json的使用有几点建议：
1. 在对话中多使用用预设的名字去称呼gpt，使其认识到正处于人格模拟模式
2. 少提及与预设相去甚远的知识，容易造成人格（上下文）污染
