### ISSUE TITLE
加载模块main.py错误？

### ISSUE THREAD

**Issue by 1458138463** [chordfish-k/emoticon#4]
![`N}%ZAH`R)8KD 3`D~QKDBP](https://user-images.githubusercontent.com/132394308/235757320-89cbf255-362c-4d7a-8c4b-0d7790e2b431.png)

**Comment by RockChinQ** [comment]
请将plugins目录下此插件的目录中的-master删掉再重启；或删除此目录后通过!plugin get指令安装

**Comment by 1458138463** [comment]
感谢大佬 解决了
